version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # KC_HOSTNAME: keycloak
      # KC_PROXY: edge
      KC_DB: dev-file
    volumes:
      - ./keycloak/data:/opt/keycloak/data
      # - ./keycloak/import:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "/opt/keycloak/bin/kc.sh", "show-config"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 40s
    networks:
      - est-network


  cassandra:
    image: cassandra:5.0.4
    container_name: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: est-cluster
      CASSANDRA_DC: dc1
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -u cassandra -p cassandra -e 'DESCRIBE keyspaces'"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - est-network

  fastapi:
    build: ./est-sale-backend
    container_name: fastapi
    environment:
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: ent-realm
      KEYCLOAK_CLIENT_ID: ent-client
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra
    ports:
      - "8000:8000"
    depends_on:
      cassandra:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - est-network

  # frontend:
  #   build: ./est-sale-frontend
  #   container_name: frontend
  #   environment:
  #     REACT_APP_KEYCLOAK_URL: http://keycloak:8080
  #     REACT_APP_KEYCLOAK_REALM: ent-realm
  #     REACT_APP_KEYCLOAK_CLIENT_ID: ent-client
  #     REACT_APP_API_URL: http://fastapi:8000
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     fastapi:
  #       condition: service_started
  #   networks:
  #     - est-network

volumes:
  cassandra_data:

networks:
  est-network:
    driver: bridge